apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dotz-tn4tn
  description: |
    serviços para testes do time de arquitetura 
spec:
  type: service
  owner: tn4tn-team
  lifecycle: production
   providesApis:
    - petstore
    - streetlights
    - hello-world
