openapi: 3.0.1
info:
  title: DotzTn4tn 1.0
  contact:
    name: Dotz Labs
    email: dotzlabs@dotz.com
  version: '1.0'
servers:
  - url: /dotz-tn4tn/api/default
paths:
  /v1/customer:
    post:
      tags:
        - Customer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DharmaError'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DharmaError'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DharmaError'
    get:
      tags:
        - Customer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DharmaError'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DharmaError'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DharmaError'
  /v1/healthcheck:
    post:
      tags:
        - HealthCheck
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DharmaError'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DharmaError'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DharmaError'
components:
  schemas:
    DharmaError:
      type: object
      properties:
        code:
          type: string
          nullable: true
        message:
          type: string
          nullable: true
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Por favor insira no campo o token JWT com Bearer.
      name: Authorization
      in: header
security:
  - Bearer: []
