apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: DotzTn4tn.API.Default
  description: API desenvolvida para ser utilizada para testes de arquitetura
  tags:
    - test
    - rest
  links:
    - url: https://dotzmkt.visualstudio.com/Dotz/_git/dotz-tn4tn
      title: Azure Git Repo
      icon: github
spec:
  type: openapi
  lifecycle: experimental
  owner: tn4tn-team
